Dev
LogNi-FinTech/loofi-auth pull request #1
Opened 2023-02-04 18:39 UTC by Ibrahim-Khan88

2023-02-11 15:16 UTC, azomshahriar requested changes

2023-02-11 15:16 UTC, azomshahriar commented on src/main/java/com/loofi/auth/jwt/TokenFilter.java
> +			String jwtToken = getToken(request);
Can't we make function more small?

2023-02-11 15:16 UTC, azomshahriar commented on src/main/java/com/loofi/auth/service/UserCredentialService.java
> +  @Autowired
Remove autowiare and add require argument constructor

2023-02-11 15:16 UTC, azomshahriar commented on src/main/java/com/loofi/auth/service/UserCredentialService.java
> +    if(userCredential != null) {
can't we make method small and format the code

2023-02-11 15:16 UTC, azomshahriar commented on src/main/java/com/loofi/auth/webconfing/Webconfig.java
> +				// .and().httpBasic();
remove

2023-02-11 15:16 UTC, azomshahriar commented on src/main/resources/application.properties
> +spring.datasource.password=ibrahim1
remove name add general username

2023-02-24 13:10 UTC, Ibrahim-Khan88 commented on src/main/resources/application.properties
> +spring.datasource.password=ibrahim1
What do you mean by general username?

2023-02-24 13:18 UTC, Ibrahim-Khan88 commented on src/main/java/com/loofi/auth/service/UserCredentialService.java
> +    if(userCredential != null) {
I think the function not looking so big. Maximum function wrap between 15-20 lines. But you can suggest me how can i make this small.

2023-09-02 17:27 UTC, azomshahriar approved these changes

2023-09-02 17:27 UTC, merged